/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NameCard } from "./NameCard";

export { NameCard__factory } from "./factories/NameCard__factory";
