/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BusinessCard } from "./BusinessCard";

export { BusinessCard__factory } from "./factories/BusinessCard__factory";
